version: '3.5'

services:
  redis:
    image: 'redis:5-alpine'
    container_name: 'redis'
    ports:
      - 6379:6379
  postgres:
    image: 'postgres:13-alpine'
    container_name: 'postgres'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=eesti_ldap
      - POSTGRES_USER=eesti_ldap
      - POSTGRES_PASSWORD=saladus
    volumes:
      - ./postgresql:/var/lib/postgresql
  eesti-ldap:
    build: .
    image: laurielias/eesti-ldap:latest
    container_name: eesti-ldap
    ports:
      - 8000:8000 # Django
    volumes:
      - .:/home/docker/eesti_ldap
    entrypoint: 'docker-entrypoint-dev.sh'
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
      - postgres
  eesti-ldap-prod:
    image: laurielias/eesti-ldap:latest
    container_name: eesti-ldap
    depends_on:
      - redis
      - postgres
    volumes:
      - ./settings.py:/home/docker/eesti_ldap/eesti_ldap/settings.py
      - ./run:/home/docker/eesti_ldap/run
      - ./static:/home/docker/eesti_ldap/static
    # ports:
    #   - 8000:8000
    # volumes:
    #   - .:/home/docker/eesti_ldap
    # entrypoint: 'tail -f /dev/null'
  eesti-ldap-celery-worker:
    build: .
    image: laurielias/eesti-ldap:latest
    container_name: eesti-ldap-celery-worker
    volumes:
      - .:/home/docker/eesti_ldap
    entrypoint: 'celery -A eesti_ldap worker -l info'
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
      - postgres
      - eesti-ldap
  eesti-ldap-celery-beat:
    build: .
    image: laurielias/eesti-ldap:latest
    container_name: eesti-ldap-celery-beat
    volumes:
      - .:/home/docker/eesti_ldap
    entrypoint: 'celery -A eesti_ldap beat -l info'
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
      - postgres
      - eesti-ldap
  eesti-ldap-celery-flower:
    build: .
    image: laurielias/eesti-ldap:latest
    container_name: eesti-ldap-celery-flower
    ports:
      - 5555:5555 # Flower UI
    volumes:
      - .:/home/docker/eesti_ldap
    entrypoint: 'celery -A eesti_ldap flower'
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
      - postgres
      - eesti-ldap
