# Generated by Django 2.1.7 on 2019-03-25 11:13

import django.contrib.postgres.fields.jsonb
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('eesti_ldap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_date', models.DateField()),
                ('possible_national_ids', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BirthHospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-85.05115),
                                                           django.core.validators.MaxValueValidator(85)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180),
                                                            django.core.validators.MaxValueValidator(180)])),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_code', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                (
                'birth_date', models.ForeignKey(on_delete='PROTECT', related_name='people', to='eesti_ldap.BirthDate')),
                ('birth_hospital',
                 models.ForeignKey(blank=True, null=True, on_delete='PROTECT', to='eesti_ldap.BirthHospital')),
            ],
        ),
        migrations.DeleteModel(
            name='IdCheckQuery',
        ),
        migrations.AddField(
            model_name='skeeldapquery',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skeeldapquery',
            name='input',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skeeldapquery',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='skeeldapquery',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
