# Generated by Django 2.2 on 2019-06-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('eesti_ldap', '0003_auto_20190325_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skeeldapquery',
            name='input',
            field=models.TextField(db_index=True, unique=True),
        ),
    ]
