# Generated by Django 2.2.19 on 2021-03-11 21:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('eesti_ldap', '0005_birthdate_search_exhausted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='birth_hospital',
        ),
    ]
